language: objective-c
env:
 global:
   - "MODULE_NAME=ti.aws"
before_install:
    - MODULE_ROOT=$PWD
install:
    - cd $MODULE_ROOT
    - curl -o install.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/install.sh
    - source install.sh
script: 
    - ./build.py
after_success: # and this only on success
  - curl -o deploy.sh https://raw.githubusercontent.com/appcelerator-modules/ci/master/travis/deploy.sh
  - source deploy.sh
